version: "3"
services:
  ubuntu:
    build:
      dockerfile: dockerfile
    container_name: ubuntunet1
    image: ubuntu
    restart: on-failure
    command: ["sleep","infinity"]
    networks:
      - net1
  ubuntu2:
    build:
      dockerfile: dockerfile
    container_name: ubuntunet2
    image: ubuntu
    restart: on-failure
    command: ["sleep","infinity"]
    networks:
      - net2

networks:
    net1:
      driver: bridge
    net2:
      driver: bridge