apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV3TURReApPRE0xTlRsYUZ3MDBNakV3TURReE9ETTFOVGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDL0pJUlR0Wm80ajBjQ0FKSm42WGZCQ3hOcUNkTldOS3F2Z3hnMVpRWHBWd1hINm9iUwppejRoMG03VHlianJrUFgxVjZEN1pCUlVkUHY3M1M3L2VaM21hV0d4bWN2d2tDWEkxSXNnMHZ4MG9iOVhmS1ZGCnpMK1VuQ3BWMkY4KzJ5dkF4a0RZNG1nRnFJRWhSRDVEMDBZc2k5cUZNL3pzQnZxVmZES3VwWHUxUGRJV2dLOTYKMUZCbWpyZTNCZGUxam5tSGE0WjVaai8raFlZRllBeVloK0x4YTVWVTZpbWVCa1JxRkFHVllPNHRyNDhsZ1BONApYZjFSclYvMG9sVkZCZXQ1NFRyMTF2YzRRVWYwTHZGRm1wR25iNVlEMStBUFFVVUVicUh0VlY4WlBTb1NTV3BMCkZFMngyaFh0c09zaEtSV3BsNEQ4UEFPV0JENXRGODZsQzFYYkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNUTFhMUWMxbmtxM1NJTEE2TwpmNzltWVFWS2VqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNZ0NVWlIxVEhSdW5MU001WE1oYU5lb3R6bENUCmdGbHlHZlpwejlPVDQvMWhmdGkrbGdmZjNTT29IL29WN1pwb1lYV1ZZNENDTU1mZHBmajhybEFKejFVU0JiNmUKU1VWSzlBbzZ1YXdCZ1lHU1JWYjhwRmorL051YUU3ancrdHIvUFNXRWZKT3pablFDMzQrNW85eWVzNExJblo3aQowc21PUDYvRGV3RzhoeExWd2xid0E4L1g3SGx3eGxiTmd1SC9xanBVWTBkbFRTbEcxdXJSNmhmbHlEUEdGYU9LCjVLVzByREx1U1NVa3lsa0x3aW9FcGJ6Tm51YTBLQW5jZWc3OTcrVFZyTVZzMTRPeWJVSVQ2VW1vZnZsRXo3Tk8KdG9EZFRLZlNLRjF2dGpsbUs2dEYxWVgwTGc2WUF4aW9LVjBCZDhhVmpLOEExdzVpeW1pUDVYNXR2dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://d79cfa8b-6505-414d-9e3d-e3f7cf698b38.k8s.ondigitalocean.com
  name: do-nyc1-k8s-1-24-4-do-0-nyc1-1664908538426
contexts:
- context:
    cluster: do-nyc1-k8s-1-24-4-do-0-nyc1-1664908538426
    user: do-nyc1-k8s-1-24-4-do-0-nyc1-1664908538426-admin
  name: do-nyc1-k8s-1-24-4-do-0-nyc1-1664908538426
current-context: do-nyc1-k8s-1-24-4-do-0-nyc1-1664908538426
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-1-24-4-do-0-nyc1-1664908538426-admin
  user:
    token: dop_v1_c6a3515bdee2ab320d784c4a6d9118ec09c63e511557076e76d070667a53594c
